name: AlongueJa
options:
  bundleIdPrefix: com.bksolucoes
configs:
  Debug: debug
  Release: release
targets:
  AlongueJa:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    settings:
      INFO_PLIST_FILE: StretchApp/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.bksolucoes.AlongueJa
    sources:
      - StretchApp
    resources:
      - StretchApp/Assets.xcassets